### ISSUE TITLE
Find way to have the Pair popup auto-accepted in Linux VM

### ISSUE THREAD

**Issue by Venryx** [Venryx/switch-resources#2]
This is important when the PC and Switch share a screen/TV (to avoid the need to switch between the TV inputs in the case of simulated-controller disconnects).

I recall that one of the threads linked in the NXBT doc talks about something like this, by patching one of the files. Ah yes, [this post](https://github.com/Poohl/joycontrol/issues/3#issuecomment-821082464), in the "Configure an Agent" section.

**Comment by Poohl** [comment]
You might be intrested in the `NoInputNoOutput` agent. While this is less secure, as it allows _anything_ to connect without confirmation or intervention, it works quite well. To prevent random passerbys connecting you have to disable `pairable` (and make sure they are not already paired). It however has to be noted, that to _pair_ the switch this has to be enabled for a brief moment.

Commands (inside `bluetoothctl`):
```
agent off
agent NoInputNoOutput
pairable off
```
And close the Ubuntu (or whatever you are using) Bluetooth settings before doing this, as they somehow overrule anything you do in the CLI.

**Comment by Venryx** [comment]
Thanks much for the tip, I will check it out.

**Comment by Venryx** [comment]
The `NoInputNoOutput` agent approach never worked for me -- the pairing popups continued to show, and needed to be pressed. (and I followed the instructions for like 5 different variants of it, found through Google searches)

However, I eventually accomplished the desired functionality by creating a short NodeJS "wrapper" program, which runs `bluetoothctl` as a child process, and just automatically types in `yes` to its input stream whenever it asks if it should authorize a pairing. (for the child-process `bluetoothctl` to actually handle the pairing requests, I had to first disable the built-in "Auth Provider?" Bluetooth plugin)

I'll keep this issue open, as I still need to add instructions for this functionality to the guide.

**Comment by Venryx** [comment]
Okay, so while searching for a post I found earlier on the subject, I just now came across this: https://sites.google.com/site/itmyshare/system-admin-tips-and-tools/expect-command-use-case-in-linux

It looks like I could have just used the "expect" command, rather than writing a NodeJS wrapper program. Good to know for the future...

**Comment by Poohl** [comment]
sorry to hear that the `NoInputNoOutput` didn't work, I know its flaky. Maybe this is also affected by BlueZ input-plugin?

**Comment by Venryx** [comment]
> Maybe this is also affected by BlueZ input-plugin?

Maybe; anyway, the wrapper program is working alright, so I'll use that for now.
